### ISSUE TITLE
Configure fork for easy updating from https://github.com/srophe/srophe-eXist-app

### ISSUE THREAD

**Issue by nathangibson** [biblia-arabica/srophe-eXist-app#1]
@wsalesky I'm not sure what the process is for updating a forked repo that has been customized. Could you take a look at the commits so far (https://github.com/biblia-arabica/srophe-eXist-app/commits/dev) and see if there's anything that needs to be adjusted before we proceed with further customization? It would also be good to document this.

**Comment by nathangibson** [comment]
P.S. I think you will have to accept my invitation before I can assign you issues.

**Comment by wsalesky** [comment]
@nathangibson I have stripped out a lot of Syriaca.org submodule specific cruft, mostly unneeded html pages and submodule folders. So far I have not removed any unneeded xquery. So it should be easy to merge in new changes from upstream as we need them. I will leave this open until I can get some documentation written.

**Comment by nathangibson** [comment]
@wsalesky Thanks!
