### ISSUE TITLE
Highlight collection browsing on bibliography home page

### ISSUE THREAD

**Issue by nathangibson** [biblia-arabica/srophe-eXist-app#102]
@wsalesky We feel that the landing page for the biblio https://biblia-arabica.com/bibl doesn't surface the browsing features very well. We'd like to ask you to redesign the layout to better highlight browsing by collection. See attached screenshot.

Under the full title, before the intro text, we'd like to have two sections with clearly visible headers: "Browse by biblical section" and "Browse by theme". Under each one we want to put the boxes that we currently have listed under "Collections." (It's fine to keep the same design for the boxes. We'll need to get you some pics for the new ones though.) Here's roughly what should go under each, with links for the ones that are new.

- Browse by biblical section
  - All https://biblia-arabica.com/bibl/browse.html
  - Old Testament https://biblia-arabica.com/bibl/browse.html?fq=;fq-Biblical%20Parts:Old%20Testament
  - New Testament https://biblia-arabica.com/bibl/browse.html?fq=;fq-Biblical%20Parts:New%20Testament
  - Pseudepigrapha https://biblia-arabica.com/bibl/browse.html?fq=;fq-Biblical%20Parts:Pseudepigrapha
  - Pentateuch https://biblia-arabica.com/bibl/browse.html?fq=;fq-Biblical%20Sections:Pentateuch
  - Historical Books https://biblia-arabica.com/bibl/browse.html?fq=;fq-Biblical%20Sections:Historical%20Books
  - Psalms https://biblia-arabica.com/bibl/browse.html?fq=;fq-Biblical%20Sections:Psalms
  - Sapiential Books https://biblia-arabica.com/bibl/browse.html?fq=;fq-Biblical%20Sections:Sapiential%20Books
  - Prophets https://biblia-arabica.com/bibl/browse.html?fq=;fq-Biblical%20Sections:Prophets
  - Gospels 
  - Pauline Epistles
  - Catholic Epistles https://biblia-arabica.com/bibl/browse.html?fq=;fq-Biblical%20Sections:Catholic%20Epistles
 - Browse by theme
   - General Introductions (instead of "Generalia" but same link https://biblia-arabica.com/bibl/browse.html?fq=;fq-Subjects:Generalia)
   - Qaraite Translations
   - Quotations in Christian Arabic Writings
   - Editions https://biblia-arabica.com/bibl/browse.html?fq=;fq-Subjects:Editions
   - Historic Printings https://biblia-arabica.com/bibl/browse.html?fq=;fq-Subjects:Historic%20Printings
   - Art, Codicology, Paleography https://biblia-arabica.com/bibl/browse.html?fq=;fq-Subjects:Art,%20paleography,%20codicology
   - Planned Additions (see existing text)

The layout is only meant as a suggestion regarding what to emphasize. Please exercise your creative freedom :-)

![Screenshot_2019-09-23 Biblia Arabica bibliography](https://user-images.githubusercontent.com/3083452/65429513-957aa380-de16-11e9-9fb0-29949b009c8d.jpg)

**Comment by nathangibson** [comment]
PS Please keep the listed "editors" in the boxes. We'll supply you with any info on editors for the new boxes.

**Comment by nathangibson** [comment]
Edited above list per conversation with Ronny.

We would like to combine some sections when we list them as suggested browse points on the homepage. Is there an "OR" operator that would show, e.g., Acts (1 item, https://biblia-arabica.com/bibl/browse.html?fq=;fq-Biblical%20Sections:Acts) *and* Pauline Epistles (40 items, https://biblia-arabica.com/bibl/browse.html?fq=;fq-Biblical%20Sections:Pauline%20Epistles) = total 41 items?

**Comment by wsalesky** [comment]
@nathangibson There is not currently an or operator for facets, I can try to add one, if you like.

**Comment by wsalesky** [comment]
@nathangibson How do you feel about a carousel approach to the browse options? The down side is that not all options will be on the page at once. 

See example: 
<img width="1422" alt="Screen Shot 2019-10-03 at 2 40 02 PM" src="https://user-images.githubusercontent.com/1168206/66154591-d24f5300-e5eb-11e9-92b6-ca3d0441ff59.png">

**Comment by wsalesky** [comment]
@nathangibson Or I can just put them as horizontal list, then they will wrap...

**Comment by nathangibson** [comment]
> @nathangibson There is not currently an or operator for facets, I can try to add one, if you like.

If it's not too much effort, that would be great. Otherwise we can label them differently in the data.

**Comment by nathangibson** [comment]
> @nathangibson How do you feel about a carousel approach to the browse options? The down side is that not all options will be on the page at once.
> 
> See example:
> <img alt="Screen Shot 2019-10-03 at 2 40 02 PM" width="1422" src="https://user-images.githubusercontent.com/1168206/66154591-d24f5300-e5eb-11e9-92b6-ca3d0441ff59.png">

Let's ask @rvollandt . I really like the overall look, just not sure if we want to force people to click through horizontally.

**Comment by wsalesky** [comment]
We can have them wrap. I think that would still look nice. I would make them a little smaller.

**Comment by nathangibson** [comment]
Yes, please try that.

**Comment by wsalesky** [comment]
@nathangibson I found the 'slide' version above to be awkward with so many slides,  here is an alternative version, let me know what you think. 
https://biblia-arabica.com/bibl/index-alt.html

**Comment by nathangibson** [comment]
@wsalesky I'll discuss with @rvollandt and get back to you.

**Comment by nathangibson** [comment]
With simpler motifs rather than text?

**Comment by wsalesky** [comment]
I will post a version with the individual images. I think it looks messy
because there are so many of them, but I will let you be the judge.
-Winona

**Comment by nathangibson** [comment]
OK, thanks. I believe you, but we might need to see it to get an idea of what to do differently :-)

**Comment by wsalesky** [comment]
@nathangibson Okay, here is one version with the individual images: 
https://biblia-arabica.com/bibl/index-alt2.html

**Comment by nathangibson** [comment]
Thanks for that. Discussed with @rvollandt and we would be intersted in trying a combo approach. We like the 2-column (index-alt) version, because it ques the user clearly about the browse options. But we do prefer the square icon pics if there aren't too many. 

Could we try keeping the 2 columns but instead of having the horizontal pic on top of each, having only 3 browse items for each with a thumbnail and the others as just text links? That way we would still give a clear choice but be highlighting the most signicant collections rather than overwhelming the page with images. Also the images can be very minimalistic - no need for borders or whatever. 

So "Browse by Biblical section" should have "All," "Old Testament," and "New Testament" with thumbnails, the rest just with text links as you have them.

"Browse by theme" should have thumbnails for "General Introductions," "Historic Printings," and "Qaraite Translations" with the rest as text links. 

Does that sound clear and doable? 

For now you could use placeholder pics and we can sub in the real ones once we're done playing with the layout. 

Thanks!

**Comment by wsalesky** [comment]
@nathangibson @rvollandt That sounds good. Will try to have something to you early this week.

**Comment by wsalesky** [comment]
@nathangibson @rvollandt 

How about this one: 
<img width="1419" alt="Screen Shot 2019-11-14 at 2 04 41 PM" src="https://user-images.githubusercontent.com/1168206/68887860-c032fb00-06e7-11ea-8852-b37d719140dc.png">

**Comment by nathangibson** [comment]
I like this direction. Will check with @rvollandt .

**Comment by nathangibson** [comment]
@wsalesky We like this! We'll get back to you with some pics. Also the picture headers in the "Browse by theme" section should be 

- [General Introductions](https://biblia-arabica.com/bibl/browse.html?fq=;fq-Subjects:Generalia) Edited by Ronny Vollandt
- [Historic Printings](https://biblia-arabica.com/bibl/browse.html?fq=;fq-Subjects:Historic%20Printings)
- [Qaraite Translations](https://biblia-arabica.com/bibl/browse.html?fq=;fq-Community%20of%20Origin:Qaraite) Edited by Michael Wechsler and Ronny Vollandt

Also please remove "Early Prints" from the "planned additions." (It is the same as historic printings.)

**Comment by wsalesky** [comment]
Great! I will make the changes as soon as I have the new images.

**Comment by wsalesky** [comment]
@nathangibson Just waiting for the final images for this, will update status bar at the same time.  See: https://github.com/biblia-arabica/srophe-eXist-app/issues/113

**Comment by wsalesky** [comment]
@nathangibson @rvollandt Just checking in on this issue, if you send me images for the home page we can get the new version up next week.

**Comment by nathangibson** [comment]
@wsalesky So sorry, have been drowning in an apocalyptic swamp the last few weeks. Will try to get to this soon!

**Comment by wsalesky** [comment]
@nathangibson No problem, I'm just trying to round up all my remaining bugs on various projects.

**Comment by nathangibson** [comment]
Thanks!

**Comment by nathangibson** [comment]
@rvollandt is working on selecting images.

**Comment by nathangibson** [comment]
@wsalesky The images for the new bibliography homepage thumbnails are finally ready!! See https://docs.google.com/document/d/13H7otx85m-5swQlbhORY4sNvyaQsiQzK8HIVB9Cbd4E/edit for a list. @rvollandt thinks these should all be CC-BY (I think in the case of the ones for Historic Printings and General Introductions these are actually public domain.)

**Comment by wsalesky** [comment]
Wonderful. I will try to get to this this week.
-Winona

**Comment by nathangibson** [comment]
Here's what I'm seeing -- looks good except I don't see the thumbnail images for the categories

![Screenshot_2020-07-10 Biblia Arabica bibliography](https://user-images.githubusercontent.com/3083452/87155933-1e869c80-c2bc-11ea-80d7-bbd67caf14ea.jpg)

**Comment by wsalesky** [comment]
@nathangibson is this on a local build? How did you pull in the changes? I see the images in the pull request (https://github.com/biblia-arabica/srophe-eXist-app/pull/116/files), so I'm not sure why they are not showing up for you.

**Comment by nathangibson** [comment]
Oh, sorry, it should have been obvious. I loaded in the home page code from the commit but not the images (face palm). Now I see them. Looks great! Checking with @rvollandt

**Comment by wsalesky** [comment]
Okay, if it looks okay to both of you, you can complete the merge and
everything should get pushed to the server. (let me know if anything goes
wrong)

**Comment by wsalesky** [comment]
@nathangibson @rvollandt Can I move this page to the production site?

**Comment by nathangibson** [comment]
@wsalesky This is looking great. But there are some small fixes. 

1. Qaraite Translations should link to https://biblia-arabica.com/bibl/browse.html?fq=;fq-Community%20of%20Origin:Qaraite
2. Please remove the link for "Planned Additions" (leaving only the text)
3. Under Planned Additions please remove Early Prints.

Thanks!

**Comment by nathangibson** [comment]
@wsalesky Thanks for the quick update and sorry for so much back and forth, but there are some changes from @rvollandt : 

1. He says "This looks a bit dense for my taste. Maybe larger script size and more spacing." I don't know, do we need to make some things stack to accomplish that? 
2. We're about to release Samaritan Translations. Can we remove that from "Planned Additions" and put it under as a linked text item underneath "Art, Codicology, Paleography"? It should be linked to https://biblia-arabica.com/bibl/browse.html?fq=;fq-Community%20of%20Origin:Samaritan and say: 
```
Samaritan Translations
Edited by Leonhard Becker
```
3. Please move the header "Introduction" underneath the stats dashboard. 
4. There is some white-on-white text in the stats dashboard only showing up if you select it. (See screenshot.) 

I _hope_ that will be all :-). You can post a screenshot before making live changes if that's easier and I'll run it by Ronny again.

<img width="967" alt="Screen Shot 2021-02-24 at 3 19 07 PM" src="https://user-images.githubusercontent.com/3083452/109013735-c61dd700-76b3-11eb-8830-f8ca059407b9.png">

**Comment by nathangibson** [comment]
Oh, and we also need to figure out the image credits - what and where they go. Forgot about that! So maybe you can do a screenshot with the above changes and I'll try to get the image credits soon.

**Comment by wsalesky** [comment]
How does this version look?

<img width="1673" alt="Screen Shot 2021-02-25 at 10 39 22 AM" src="https://user-images.githubusercontent.com/1168206/109177439-ce2e5300-7755-11eb-947b-94ecbf62ba6d.png">

**Comment by rvollandt** [comment]
Dear Winona, 

 

Yes, thanks! Samaritan translation need the addition “edited by Leonhard Becker”, similarly to the Gospels and Pauline Epistles on the left. 

 

Thank you,

Ronny

 

Von: Winona Salesky <notifications@github.com>
Antworten an: biblia-arabica/srophe-eXist-app <reply@reply.github.com>
Datum: Donnerstag, 25. Februar 2021 um 16:42
An: biblia-arabica/srophe-eXist-app <srophe-eXist-app@noreply.github.com>
Cc: rvollandt <ronny.vollandt@lmu.de>, Mention <mention@noreply.github.com>
Betreff: Re: [biblia-arabica/srophe-eXist-app] Highlight collection browsing on bibliography home page (#102)

 

How does this version look?

**Comment by wsalesky** [comment]
The requested changes have been made.

**Comment by nathangibson** [comment]
Thanks @wsalesky . 

A tiny thing: For some reason "edited by Leonhard Becker" is a different font size from the other "edited by" bylines.

Here are the image credits.  I would suggest this go simply as an unobtrusive text paragraph at the bottom of the page, after the "Contributors" section. Unless @rvollandt has a different suggestion: 

Image credits: All: [Vatican, Biblioteca Apostolica Vaticana, Barb.or.2](https://digi.vatlib.it/view/MSS_Barb.or.2/0010), f. 2v; Old Testament: [Berlin, Staatsbibliothek zu Berlin, Diez A fol. 41, f. 95r](http://resolver.staatsbibliothek-berlin.de/SBB0000D4AC00000195) (public domain); New Testament: [Berlin, Staatsbibliothek zu Berlin, Wetzstein I 184, 8r](http://resolver.staatsbibliothek-berlin.de/SBB0001F56B00000017) ([CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0)); General Introductions: [Paris, Bibliothéque nationale de France, Ar. 6](https://gallica.bnf.fr/ark:/12148/btv1b10538491d/f14), f. 1v (public domain, source BNF/Gallica); Historic Printings: [Thomas Erpenius (ed.), Pentateuchus Mosis, Arabice (Lugduni Batavorum: ex typogr. Erpeniana, 1622), 2](https://hdl.handle.net/2027/ucm.5325325873?urlappend=%3Bseq=30) (public domain); Qaraite Translations: [Cambridge, Cambridge University Library, Or.1080 1.67, f. 1r](https://cudl.lib.cam.ac.uk/view/MS-OR-01080-00001-00067/1)

**Comment by wsalesky** [comment]
Fixed.

**Comment by nathangibson** [comment]
Looking great. I'll close this and we'll reopen if @rvollandt has any fixes.
