### ISSUE TITLE
Remove URLs in citation box

### ISSUE THREAD

**Issue by nathangibson** [biblia-arabica/srophe-eXist-app#103]
Since we have the "View at" link, Ronny would like for us to remove the URL that appears inside the "Preferred Citation" box. 
I believe in some cases Zotero automatically includes the item from the URL field in the citation that we're grabbing, so you'd have to strip it out. Is that okay, or is it something we need to change on the data side?
E.g., https://biblia-arabica.com/bibl/VC847CSA

**Comment by nathangibson** [comment]
However, I think our converter is making DOIs into links. In this case (e.g. https://biblia-arabica.com/bibl/7UTHFEXT) can we include them down with the URI, formatted as a DOI but with clickable link? It would look like 

> DOI: [10.1111/j.1478-1913.1943.tb01311.x](https://doi.org/10.1111/j.1478-1913.1943.tb01311.x)

**Comment by wsalesky** [comment]
Resolved in the new version of https://github.com/biblia-arabica/zotero2bibl/blob/master/zotero2tei.xqm 

You will need to add these to the config file: 
```
    <altgroupid>538215</altgroupid>
    <altgroupid>biblia_arabica</altgroupid>
```

**Comment by wsalesky** [comment]
@nathangibson run and test results. Close if it is resolved.

**Comment by nathangibson** [comment]
Hmm, unfortunately I tried running this and it did nothing. I wondered if it was maybe the regex escaping on the curly brackets {} -- in Oxygen the regex matches only if the brackets are not escaped. But when I tried removing the escaping, I got a 400 error response when I tried to run it -- something about regex escaping in Java. So I'm not sure what the problem is.

**Comment by wsalesky** [comment]
These changes are showing up for me on my most recent run of the data, are you running the script with elevated privileges? If not run the following in eXide (as admin): 

`sm:chmod('/db/apps/zoter2bibl/get-zotero-data.xql'), "rwsr-xr-x")`

I have also added this to the zotero2bibl library so it should add these permissions when the app is deployed. 

<img width="882" alt="Screen Shot 2019-09-27 at 9 23 09 AM" src="https://user-images.githubusercontent.com/1168206/65772571-79be1880-e108-11e9-9194-e15e2f14c187.png">

**Comment by nathangibson** [comment]
Unfortunately I get the following error message when I install the latest zotero2bibl app:

> Error found while processing repo.xml: exerr:ERROR Permission to modify permissions is denied for user 'admin' on '/db/apps/zotero2biblget-zotero-data.xql': exerr:ERROR Resource or collection '/db/apps/zotero2biblget-zotero-data.xql' does not exist. [at line 19, column 1]

It looks like it needs another slash in the file path?

**Comment by wsalesky** [comment]
Sorry, you are correct, it was a bad path. Try now.

**Comment by nathangibson** [comment]
Success! Installation was flawless and it looks like the results are as expected. 
https://github.com/biblia-arabica/biblia-arabica-data/commit/75ca5dcc5a6490331c73a75e6028fd82118aa78b
Will wait until tomorrow to load onto the live server as I seem to break things when I try it at the end of the day :-)

**Comment by wsalesky** [comment]
Great! Sorry about the typo!

**Comment by nathangibson** [comment]
Okay, got the latest package loaded. Some changes are as expected. However, I might not have adequately explained what we'd like to happen with the DOIs. 
Right now they're showing up as a link under "View at" and also as plain text next to "DOI:". We would like to supress the "View at" link for DOIs but make the text next to "DOI:" clickable.

<img width="478" alt="Bildschirmfoto 2019-10-02 um 12 29 04" src="https://user-images.githubusercontent.com/3083452/66037873-e3776180-e510-11e9-9901-49d4560a8ed1.png">

The link target (adding "https://doi.org/" to the DOI) could be added either in the stylesheet or in the data. I think it would be better in the data. E.g., 

```
<!-- This should be the target of the clickable link  -->
<idno type="URI">https://doi.org/10.1111/j.1478-1913.1943.tb01311.x</idno>
<!-- This should display as the text of the link after "DOI: " -->
<idno type="DOI">10.1111/j.1478-1913.1943.tb01311.x</idno>
```
But I'm open to other options. 

The reason to supress the "View at" link is that if an item only has a DOI link, it is probably behind a paywall since our policy is to add the URL of open-access items.

The reason we don't want a normal https link text displayed on the page is that (1) @rvollandt thinks it is getting too cluttered with all the URLs and (2) the DOI is a special type of identifier that is resolvable but can also stand alone. So it should look like 

> DOI: [10.1111/j.1478-1913.1943.tb01311.x](https://doi.org/10.1111/j.1478-1913.1943.tb01311.x)

I think you already have some rules being applied for which domains show in the "View at" box? And you are already doing something different with the Zotero idnos. So I assume something like this should be possible using the mechanisms you have in place?

**Comment by wsalesky** [comment]
@nathangibson this is an easy fix. Just to clarify, do you want both tei:idno elements shown in your example? Or should I just create the link in the XSLT?

**Comment by nathangibson** [comment]
@wsalesky Thanks. Yes please include both tei:idnos.

**Comment by wsalesky** [comment]
@nathangibson Done.
