### ISSUE TITLE
Error on search

### ISSUE THREAD

**Issue by nathangibson** [biblia-arabica/srophe-eXist-app#104]
E.g. https://biblia-arabica.com/bibl/search.html?q=test gives me 
`err:XPDY0002 variable '$sort-element' is not set. [at line 51, column 68, source: /db/apps/ba/modules/search/search.xqm]`

**Comment by wsalesky** [comment]
Fixed by : https://github.com/biblia-arabica/srophe-eXist-app/commit/168fda5b9da92cfd5e4744dd9ad99773a6c55c2a
