### ISSUE TITLE
Convert links in abstracts

### ISSUE THREAD

**Issue by nathangibson** [biblia-arabica/srophe-eXist-app#106]
I thought I had put this in the conversion script but I guess not ...

Where we've linked in the Abstract field to other items, we've done so using the Zotero URI in curly braces. E.g. https://biblia-arabica.com/bibl/5MCGFR9K Abstract says 

> Review of {https://www.zotero.org/groups/biblia_arabica/items/itemKey/HCW9SRAH}.

Can we have the conversion script change these to the biblia-arabica.com URIs with clickable links? So it should be 

> Review of [https://biblia-arabica.com/bibl/HCW9SRAH](https://biblia-arabica.com/bibl/HCW9SRAH).

**Comment by wsalesky** [comment]
@nathangibson do you want this in the Zotero script or the conversion from TEI to HTML? (I recommend the Zotero so it is correct in the TEI, either a ref or ptr element.)

**Comment by nathangibson** [comment]
Yes, in the Zotero script. I think we would want a ref, right?

**Comment by wsalesky** [comment]
@nathangibson Yes I think ref is what we want. I have a few changes to make to the Zotero script. Hopefully I can get them all done today and you can rerun the script by tomorrow.

**Comment by wsalesky** [comment]
@nathangibson  
Resolved in the new version of https://github.com/biblia-arabica/zotero2bibl/blob/master/zotero2tei.xqm

You will need to add these to the config file:
```

    <altgroupid>538215</altgroupid>
    <altgroupid>biblia_arabica</altgroupid>
```

**Comment by nathangibson** [comment]
Done. Thanks!

**Comment by nathangibson** [comment]
Some of these were successful, e.g., https://biblia-arabica.com/bibl/TETNIZR6

But in some of them have remained Zotero links, e.g., https://biblia-arabica.com/bibl/XCALY2N8 containing {https://www.zotero.org/groups/538215/biblia_arabica/items/itemKey/QEFP6HVN} and https://biblia-arabica.com/bibl/X9S78ZWR containing {https://www.zotero.org/groups/538215/biblia_arabica/items/itemKey/K6G37MNV}. As far as I can tell the regex in https://github.com/biblia-arabica/zotero2bibl/blob/master/zotero2tei.xqm#L322 should have matched these as well.

**Comment by wsalesky** [comment]
@nathangibson I will take a look.

**Comment by wsalesky** [comment]
@nathangibson I see the problem, the group id string for the non matching URL is : 538215/biblia_arabica 
See: https://www.zotero.org/groups/538215/biblia_arabica/items/itemKey/QEFP6HVN 

You would have to add that as an additional altgroupid in the config file. (I tested it and it works. )

**Comment by nathangibson** [comment]
Looks like this worked. Managed to crash the server trying to update the data app though :-(

**Comment by nathangibson** [comment]
OK, server back up and the new records look good!

**Comment by wsalesky** [comment]
Great!
