### ISSUE TITLE
IIIF Viewer??

### ISSUE THREAD

**Issue by nathangibson** [biblia-arabica/srophe-eXist-app#107]
We would **love** to incorporate a IIIF viewer where IIIF manifests are available, so that users can see items inline in our bibliography. Do you think this is doable? 

We could start with archive.org items. Documentation is here http://iiif.archivelab.org/iiif/documentation and here https://archive.readme.io/docs/ia-iiif-faqs. 

An example would be https://biblia-arabica.com/bibl/K6G37MNV with IIIF manifest at https://iiif.archivelab.org/iiif/arabicversionofe00gibs/manifest.json. 

I don't know which viewer could be most easily incorporated. Here are the ones I know of:
Leaflet-IIIF: https://showcase.iiif.io/showcase/leaflet-iiif-viewer/ 
OpenSeaDragon: https://openseadragon.github.io 
Mirador demo: http://projectmirador.org/demo (IIIF viewer)
Universal Viewer: https://universalviewer.io/

**Comment by wsalesky** [comment]
@nathangibson I will investigate.

**Comment by wsalesky** [comment]
@rvollandt @nathangibson Do you have a favorite, or a list of features you want supported? I think we could easily implement  any of the above, but should chose one based on desired features.

**Comment by millertg** [comment]
@wsalesky @rvollandt @nathangibson Hi All! I am very new at all of this, but Mirador is being used in the 10,000 Rooms project at Yale (https://tenthousandrooms.yale.edu), which may have useful functionality. On the MIrador homepage, they say they use Openseadragon for visual navigation (https://projectmirador.org/).  I am uncertain what that would mean for implementing within Srophe, however.

**Comment by nathangibson** [comment]
Thanks @wsalesky and @millertg ! Glad to collaborate on this.

At present our main purpose is displaying multi-page books or articles for people to be able to read directly on the site. @millertg are the architectural plans you want to display generally single images or multi-page items? 

For us and perhaps other users of the Srophe app, viewing manuscripts or inscriptions would be another likely scenario down the road. 

After looking at these different viewers, Leaflet and Openseadragon don't seem to have good features for reading multi-page items. Between Mirador and Universal Viewer it's a close call. UV has a nice "jump to page" feature where you can just enter in the page you want to go to. It also supports IIIF Auth, which we don't currently need but perhaps in the future ...

On the other hand, Mirador loads my test manifest *much* faster in both version 2 and 3 of the demo viewer. UV seems to be extremely slow loading it (on their demo site at least). 

It looks like full-text search is in development for Mirador 3 (see https://library.stanford.edu/blogs/stanford-libraries-blog/2019/05/introducing-mirador-3-next-generation-image-comparison-viewer) and possibly IIIF Auth (see https://github.com/ProjectMirador/mirador-design/issues/19). 

Mirador also supports user annotations -- currently we don't have a use for this though.

On the whole, I think loading speed is a major factor, so I would lean toward Mirador. @wsalesky do you perhaps know whether there's a speed difference or want to run any tests yourself?

**Comment by wsalesky** [comment]
@nathangibson @millertg I will run some tests with Mirador and UV and get back to you here on which I think performs faster.

**Comment by millertg** [comment]
@cliffordanderson  I think Cliff Anderson might be able to help us with this, too, so I am inviting him to join.

**Comment by CliffordAnderson** [comment]
@millertg Thanks for including me on this conversation. I look forward to your thoughts vis-a-vis Mirador and UV, @wsalesky

**Comment by wsalesky** [comment]
@CliffordAnderson is the library using any of the above options?

**Comment by CliffordAnderson** [comment]
No, we are not using any IIIF clients. We have Canteloupe set up in the context of Islandora, but that's it as far as I'm aware.

**Comment by wsalesky** [comment]
@nathangibson @millertg So far it looks like Mirador is very easy to set up and use. We will need to discuss how the images will be referenced in the TEI so I can add the actual functionality.

**Comment by nathangibson** [comment]
Catching up on old issues ... 
I would suggest archive.org as a test case -- some of our items are viewable there. E.g. https://biblia-arabica.com/bibl/L6IWVR88.tei

The archive.org link is under /TEI/text/body/biblStruct/*[1]/ref/@target (please double-check)

The link (in this case http://archive.org/details/cataloguscodicu00sinagoog) can be turned into a IIIF request by replacing `https?://archive\.org/details` with https://iiif.archivelab.org/iiif, e.g., 
https://iiif.archivelab.org/iiif/cataloguscodicu00sinagoog.

Should we systematically add archive.org IIIF links to our bibl records? And then the stylesheet could simply look for this `ref/@type`. Perhaps a parallel ref with type, e.g.,
```
<ref type="IIIF" target="https://iiif.archivelab.org/iiif/cataloguscodicu00sinagoog"/>
```
Is there a better semantic way to do this?

**Comment by nathangibson** [comment]
For reference, another group of items we can pull in with IIIF is "Digitale Sammlungen" which have URLs in the format 
http://reader.digitale-sammlungen.de/resolve/display/{ID}.html (e.g., http://reader.digitale-sammlungen.de/resolve/display/bsb10815059.html)
or http://mdz-nbn-resolving.de/urn:nbn:de:bvb:12-{ID}-{page} (e.g., http://mdz-nbn-resolving.de/urn:nbn:de:bvb:12-bsb10815059-0)

The IIIF manifest can be retrieved using the ID here: https://api.digitale-sammlungen.de/iiif/presentation/v2/{ID}/manifest e.g., https://api.digitale-sammlungen.de/iiif/presentation/v2/bsb10815059/manifest
German documentation here: https://app.digitale-sammlungen.de/bookshelf/help

**Comment by wsalesky** [comment]
@nathangibson I think the ref@type='IIIF' would work well. If you want to start marking up the bibl records I can add the code to the application.

**Comment by nathangibson** [comment]
@wsalesky Done. You can see some records to test out here: https://github.com/biblia-arabica/srophe-eXist-app/issues/107

Can you test this locally? 

Not sure what the best way to incorporate this into the Zotero import would be. I don't really want to have to add IIIF links manually in Zotero. And it seems clunky to add known IIIF providers to the converter and match against that, but I don't think of an alternative. Do you? Perhaps the list belongs in a separate file accessed by the zotero2bibl app?

**Comment by wsalesky** [comment]
@nathangibson How do you want users to access the IIIF images? A link along the top near the print/TEI/RDF/Cite buttons? Some other way?

**Comment by nathangibson** [comment]
@wsalesky 
If possible, I think we'd want the IIIF view actually embedded in the item detail page, perhaps under the Abstract but before Full Citation Information? 

If that's not possible (or advisable) perhaps we could have a large static thumbnail with a "read online" overlay that functions as a button linking to the IIIF?

In any case the IIIF should be immediately obvious, since it's intended as a convenience feature eliminating the step of users having to go to an external site for the item.

**Comment by wsalesky** [comment]
I will experiment and see what can be done.

**Comment by wsalesky** [comment]
@nathangibson @rvollandt example of the IIIF Mirador viewer in the record. Another option would be to have a thumbnail and link to a full page version of the viewer. The Mirador viewer does not always play well with Bootstrap. Let me know what you think. And when what the data will look like so I can write a hook in the xquery.

**Comment by wsalesky** [comment]
@nathangibson I will take a look, that is an xquery issue, looks like some imported modules are not resolving correctly. In the mean time, I meant to post a link in the above comment. Here it is: 
https://biblia-arabica.com/bibl/iiifDemo.html

**Comment by nathangibson** [comment]
@wsalesky This is awesome! It will provide such a convenient feature for our readers :-) 

1. **First reactions on the interface:** It suits the look of our site really well. I'm not sure what is easily customizable, but the following tweaks would be great if they're built-in options:
  1.1. Default view: Single
  1.2. Default thumbnails: Right
  1.3. "Maximized" window (hiding outer left sidebar) *if* the full-screen button can be available somewhere else
  1.4. Up & down buttons for previous/next (this will probably be more compatible with the unpredictable directional settings for scans of Arabic items)
  1.5. Green instead of blue accent color
If these aren't customizable out-of-the-box don't worry about it right now.
2. **Data hooks:** Above we discussed using a `ref/@type="IIIF"`. I'm thinking about the best way to get this into our Zotero workflow. Entering these manually in Zotero would be a pain and error-prone. The URLs are provider-based, so could we have a kind of lookup table in the Zotero2TEI that does a regex find/replace on the the URL provided from Zotero ( which is currently `ref/@target` in the TEI)? The table would look something like 

| Find | Replace |
| --- | --- |
| https?://archive\.org/details/(.*) | https://iiif.archivelab.org/iiif/$1/manifest.json |

**Comment by wsalesky** [comment]
@nathangibson 

Here are the customizations I was able to do: 
https://biblia-arabica.com/bibl/iiifDemo.html

I will take a look at the data and see how this can be automated for the records, can you give me an example Zotero record to use?

**Comment by nathangibson** [comment]
@wsalesky Wow! Looks great!

Here's an example: https://biblia-arabica.com/bibl/K6G37MNV = https://www.zotero.org/groups/538215/biblia_arabica/items/K6G37MNV which already has URL https://archive.org/details/arabicversionofe00gibs and needs IIIF manifest at https://iiif.archivelab.org/iiif/arabicversionofe00gibs/manifest.json

**Comment by wsalesky** [comment]
@nathangibson  This has been added. Can you check a few records you know it should be working on?

**Comment by nathangibson** [comment]
@wsalesky Awesomeness! 

https://biblia-arabica.com/bibl/EVURSLZ4 gives an error. It appears that https is required for archive.org, i.e., https://iiif.archivelab.org/iiif/b30542704/manifest.json rather than http://iiif.archivelab.org/iiif/b30542704/manifest.json

How should I provide you the lookup table for the few other services besides archive.org?

**Comment by wsalesky** [comment]
In the issue would be fine.

**Comment by nathangibson** [comment]
| Find | Replace | Example |
| --- | --- | --- |
| `https?://reader.digitale-sammlungen.de/resolve/display/(.*?).html` | `https://api.digitale-sammlungen.de/iiif/presentation/v2/$1/manifest` | https://biblia-arabica.com/bibl/VC847CSA |
| `https?://mdz-nbn-resolving.de/urn:nbn:de:bvb:(\d+)-([a-z0-9]+)-([a-z0-9]+)` | `https://api.digitale-sammlungen.de/iiif/presentation/v2/$2/manifest` | https://biblia-arabica.com/bibl/GJ2PTPI4 |
| `https?://www.mdz-nbn-resolving.de/urn/resolver.pl?urn:nbn:de:bvb:(\d+)-([a-z0-9]+)-([a-z0-9]+)` | `https://api.digitale-sammlungen.de/iiif/presentation/v2/$2/manifest` | https://biblia-arabica.com/bibl/H35M782P |
| `https://gallica.bnf.fr/(ark:/[A-Za-z0-9]+/[A-Za-z0-9]+)(.*)` | `https://gallica.bnf.fr/iiif/$1/manifest.json` | https://biblia-arabica.com/bibl/IRHBE8AE |

If it is possible to set the start page, this is available in nos. 2 and 3 with regex captured group $3. 

These are the ones I come up with now. If you let me know where these live I can add more later if I come across them.

**Comment by nathangibson** [comment]
@wsalesky Great! Except I don't get a IIIF viewer for https://biblia-arabica.com/bibl/H35M782P for some reason ...

**Comment by wsalesky** [comment]
Check the URL, If it does not show up, it does not match the current
patterns.
