### ISSUE TITLE
Hide See also and Zotero URIs

### ISSUE THREAD

**Issue by nathangibson** [biblia-arabica/srophe-eXist-app#108]
@wsalesky We're getting a lot of extra clutter in the URIs and See Also under "Full Citation Information" on the item detail page. E.g. https://biblia-arabica.com/bibl/X9S78ZWR 

Can we 
 1. Eliminate the "see also" link since people can already get to this via the "View At" button.
 2. Put one of the Zotero links (whichever is more stable) as a "See Zotero entry" button at the bottom of the page, after the "Full Citation Information" section. Hide the other Zotero URI. 

These URIs should remain in the TEI code but just not be visualized.

**Comment by nathangibson** [comment]
In other words we want only the Biblia Arabica URI visualized as the "URI"

**Comment by wsalesky** [comment]
Done!

**Comment by nathangibson** [comment]
Thanks!
