### ISSUE TITLE
Visualize bibliography progress on home page

### ISSUE THREAD

**Issue by nathangibson** [biblia-arabica/srophe-eXist-app#113]
While you're doing work on the home page (#102 ) ...

We would like to visualize on the home page the progress of the editing work, as is done at https://web.nli.org.il/sites/NLIS/en/ManuScript. (see screenshot) This should be fairly prominent but not overwhelming.

What you've done with the text, e.g., "348 out of 1546 online" is a good start. This might say, for example, "348 entries online", "1,198 entries in process" (= 1546 total-348), "23% complete"

![Screenshot_2019-10-21 Ktiv – The International Collection of Digitized Hebrew Manuscripts](https://user-images.githubusercontent.com/3083452/67194773-0bfbc880-f3f8-11e9-857b-640759b7c8a4.png)

**Comment by wsalesky** [comment]
@nathangibson How do I know how many entries are in process?

**Comment by nathangibson** [comment]
@wsalesky Sorry for the delay. Got this just before going on vacation. 

Entries in process are total number of items (not including notes/attachments) in Zotero library. So you should be able to get that with an API call (but it will need to use the altgroupID, i.e., the one that doesn't include the collections subdirectory).

**Comment by nathangibson** [comment]
Sorry correction: the entries in process are simply the total entries *minus* the ones that are "online". The current page already grabs these numbers ("356 out of 1546"), it just needs to do the math and visualize it more nicely :-)

**Comment by wsalesky** [comment]
@nathangibson Sorry for the delay! Working on the rest of these issues this month, will get them all finished by the end of the month. I have a counter working but will wait to fully style it until the new home page is ready, I think I need some additional images? 

Here it is so far. Numbers will update automatically. (Note, this is my local install, I do not have the full data set uploaded, hence the 5%): 
<img width="1266" alt="Screen Shot 2020-01-06 at 1 09 58 PM" src="https://user-images.githubusercontent.com/1168206/71838082-0cfed680-3086-11ea-8aac-f19a340c17fe.png">

**Comment by wsalesky** [comment]
@nathangibson @rvollandt Checking in on this issue. If you get me the new images for the home page we can have the new version up by the end of the week.

**Comment by wsalesky** [comment]
Marking as done. Will go live when we push the new home page (https://github.com/biblia-arabica/srophe-eXist-app/issues/102), which is waiting for approval from @nathangibson and/or @rvollandt
