### ISSUE TITLE
Resolve bugs introduced by design updates

### ISSUE THREAD

**Issue by wsalesky** [biblia-arabica/srophe-eXist-app#133]
Reminder to all editors, HTML pages must be XHTML pages. All tags must be closed and special characters must be escaped, otherwise eXist will simply store the pages as a binary resource and be unable to render it via the templating system.

**Comment by nathangibson** [comment]
> Reminder to all editors, HTML pages must be XHTML pages. All tags must be closed and special characters must be escaped, otherwise eXist will simply store the pages as a binary resource and be unable to render it via the templating system.

Passing this along to the @biblia-arabica/design team. Thanks @wsalesky!

**Comment by nathangibson** [comment]
Thanks @wsalesky!
