### ISSUE TITLE
Change footer citation guidance

### ISSUE THREAD

**Issue by nathangibson** [biblia-arabica/srophe-eXist-app#16]
The footer of all citation entries says

> Editorial Responsibility:
> 
>     Ronny Vollandt, general editor, Biblia Arabica
>     Ronny Vollandt and Nathan P. Gibson, editors, **Syriaca.org Works Cited**

Can we change "Syriaca.org Works Cited" to "A Bibliography of the Arabic Bible"?

I think the culprit is https://github.com/biblia-arabica/srophe-eXist-app/blob/master/srophe-app/resources/xsl/citation.xsl#L294. Perhaps another candidate for abstraction in the srophe app?

**Comment by wsalesky** [comment]
Resolved, but leaving open as a reminder to add further abstraction into the XSLT.

**Comment by wsalesky** [comment]
Fixed. This is now a variable. See: d66faf3fe690ca6094f6aa48e07d266bba3098ce 057a14624b884c0175a5fb86b7af9d268b9bc30b  9485dfe34a6e4197ad43ce412fb29fdffef38ee9
