### ISSUE TITLE
TEI button 405 error

### ISSUE THREAD

**Issue by nathangibson** [biblia-arabica/srophe-eXist-app#18]
Is the TEI button (e.g. http://localhost:8080/exist/apps/ba/bibl/432/tei) supposed to work on localhost or only on a server? It is giving the following error:

> HTTP ERROR 405
> 
> Problem accessing /exist/apps/ba/bibl/432/tei. Reason:
> 
>     HTTP method GET is not supported by this URL

**Comment by wsalesky** [comment]
To fix this you will either have to rebuild and deploy the app or update the rest.xql file and run the following code in eXide (this will redeploy the restxq code. ): 

```
xquery version "3.0";
import module namespace xrest="http://exquery.org/ns/restxq/exist" at "java:org.exist.extensions.exquery.restxq.impl.xquery.exist.ExistRestXqModule";
xrest:register-module(xs:anyURI('/db/apps/ba/modules/rest.xqm'))
```
You will also need to install the 'SPARQL and RDF indexing for eXist-db' pacakge, available from the package manager in the eXist dashboard. 

Let  me know if you still have trouble. 
Also in related news, you can add additional formats to a record with the following function added to the record.html page: 

`<div data-template="app:other-data-formats" data-template-formats="print,tei,rdf,ttl"/>`

Include only the formats you want to see in the comma separated list.

**Comment by nathangibson** [comment]
Thanks, will try this if I get time.
