### ISSUE TITLE
Include Zotero URI on entry detail page

### ISSUE THREAD

**Issue by nathangibson** [biblia-arabica/srophe-eXist-app#19]
It would be nice to include the Zotero URI after the biblia-arabica URI on the entry detail page. E.g., http://biblia-arabica.com/bibl/432 would have https://www.zotero.org/groups/538215/biblia_arabica/items/collectionKey/9MBBGCGK/itemKey/H9PTUV6K

**Comment by wsalesky** [comment]
The Zotero ID is not in the TEI. (Unless I am missing it?) We will have to add it to the new conversion script.

**Comment by nathangibson** [comment]
This is supposed to be this line https://github.com/biblia-arabica/zotero2bibl/blob/master/zotero2tei.xqm#L90. Note I am not talking about an ID tag in Zotero but rather the address for the resource on zotero.org.

**Comment by wsalesky** [comment]
This works out of the box as long as the link is in the data. It is included in the new version of the data. See: https://github.com/biblia-arabica/biblia-arabica-data/tree/issue4
