### ISSUE TITLE
Create a separate box for manuscripts on the item page

### ISSUE THREAD

**Issue by nathangibson** [biblia-arabica/srophe-eXist-app#2]
Right now we are using tags with the format "MS: ..." to indicate which manuscripts are relevant to a particular bibliographic item. 

We would like these to appear as subjects on the page, but in a separate box from the subjects. 

We will want to be able to browse and search by manuscripts (I will make a separate issue), and later we hope to build a database of manuscripts, but this is a ways off. With this in view, if you think it would be better to create URIs for manuscripts now, let me know and we can do that rather than using the shelfmark string.

**Comment by wsalesky** [comment]
@nathangibson I think we need to make some changes to the Zotero to TEI transform to handle the different types of notes. For example in 1.xml I see: 

```
                <note type="tag">Subject: Generalia</note>
                <note type="tag">!no abstract</note>
                <note type="tag">ID: 1</note>
                <note type="tag">MS: Berlin, Staatsbibliothek, Violet fragment</note>
                <note type="tag">MS: Cambridge, CUL, T-S Ar. 1a.55.</note>
                <note type="tag">MS: Istanbul, Süleymaniye, Carullah 3</note>
```
We could add the subject to the teiHeader//keywords ?
The id should probably be stripped as unnecessary? 
I'm not sure what the best way to handle the MS notes. We could create URIs and add relations but there may be an easier way to deal with them as they are not yet separate entities. If nothing else they could be transformed as note/@type='MS'. Would it make any sense to encode it as a nested bibl, similar to how we handled them in NHSL?

**Comment by nathangibson** [comment]
1. Regarding subjects, I guess this could be added to the header for now as you suggest. Later we might want to use URIs for them, but we're not there yet.
2. Is it the case that we will be able to use the final string in the Zotero URI as the ID we build our URI on (as was suggested for Syriaca)? If so, then yes, the ID can be stripped. 
3. I think having them as a relation, which could later be easily turned into URIs, would make sense. But I'm trying to figure out where we could put the relation in a biblStruct element. The only think I can figure out without changing the schema is putting the entire biblStruct inside a listBibl and then including a listRelation as the last child of listBibl? Any other ideas? I would suggest the following relation format:
```
<listRelation>
               <relation ref="dcterms:references">
                  <desc>Berlin, Staatsbibliothek, Violet fragment</desc>
               </relation>
            </listRelation>
```

**Comment by wsalesky** [comment]
1. Okay, lets add them to the header. This is the syntax (http://www.tei-c.org/release/doc/tei-p5-doc/en/html/examples-keywords.html): 

```
        <profileDesc>
            <textClass>
                <keywords scheme="#lcsh">
                    <list>
                        <item></item>
                    </list>
                </keywords>
                <classCode scheme="#lc"></classCode>
            </textClass>
        </profileDesc>
```
Are you using a controlled vocabulary? If so we can reference it in the scheme attribute. 

2. Currently the zotero2bibl library outputs an incremental idno for the 'local' id and a zotero idno
ex: `http://zotero.org/groups/538215/items/EMUXFUUM`

3. I think listRelation method of adding manuscripts is okay, nothing better is springing to mind at any rate.

**Comment by nathangibson** [comment]
1. Sorry, but I think I am changing my mind on how to do keywords. Has Syriaca (i.e., @dlschwartz) given you any direction on how they will link bibliographic items to the taxonomy module? If not, I think it would probably be good to use listRelation for this too. It will have a few advantages: similar implementation as manuscript tagging, and better upgrading to using URIs including with RDF relation features. We do not yet have a controlled vocabulary. I am working on that. If it would help to assign these as URIs (rather than text labels) from the start, let me know and I can do that.
2. OK, so there's no need for us to maintain an ID as a tag in Zotero because we could always just use the Zotero idno if we need to refer to the item, right? 
3. I'm trying to put a listRelation in the body after biblStruct, but Oxygen doesn't like it. As far as I can tell it's supposed to be allowed http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-listRelation.html

**Comment by nathangibson** [comment]
What do you think of the following relation format for the tags that will go in the subject and manuscript boxes? (It occurs to me that some of the subjects are persons, and some are even other bibliographic items.)
```

               <!--Keywords-->
               <relation active="http://biblia-arabica.com/bibl/1" ref="dc:subject">
                  <desc><term>Historic Printings</term></desc>
               </relation>
               <!--Persons-->
               <relation active="http://biblia-arabica.com/bibl/1" ref="dc:subject">
                  <desc><persName>Solomon Schechter</persName></desc>
               </relation>
               <!--Other Bibliographic Items-->
               <relation active="http://biblia-arabica.com/bibl/1" ref="dc:subject" passive="http://biblia-arabica.com/bibl/2">
                  <desc><bibl>Kirsten (1608)</bibl></desc>
               </relation>
               <!--Manuscripts-->
               <relation active="http://biblia-arabica.com/bibl/1" ref="dcterms:references">
                  <desc><bibl>Berlin, Staatsbibliothek, Violet fragment</bibl></desc>
               </relation>
```
As we assign URIs to these things (probably in a year or two), we could simply add a `@passive` to the relation.

**Comment by nathangibson** [comment]
It is not too hard to assign URIs--if they don't have to resolve to anything yet?

**Comment by wsalesky** [comment]
No, they are just ids, and more likely to be consistent then free text.

**Comment by nathangibson** [comment]
OK, then I think you can write this with the assumption that we will use URIs (as passive values). I will work on minting some--for now there isn't good data for you to test on though. 

How would you suggest inputting the data on the Zotero side? What about tags something like:
Subject: Historic Printings [http://biblia-arabica.com/keyword/historic-printings]
Subject: Solomon Schechter [http://biblia-arabica.com/person/1]
Subject: Kirsten (1608) [http://biblia-arabica.com/bibl/1]
Subject: Berlin, Staatsbibliothek, Violet fragment [http://biblia-arabica.com/manuscript/1]

So anything with "Subject: " prefix should parse the following text as the relation desc and the URI (in square brackets) as the passive URI?

**Comment by nathangibson** [comment]
In case it helps, I've tried this in this example: https://www.zotero.org/groups/538215/biblia_arabica/items/itemKey/4ZD2I7PH

**Comment by wsalesky** [comment]
Done.
