### ISSUE TITLE
Add "View at" button

### ISSUE THREAD

**Issue by nathangibson** [biblia-arabica/srophe-eXist-app#20]
Unlike the Syriaca Works Cited module, which functions at the moment mainly as a way to pull citations into other records, this bibliography is primarily for people to find stuff. 

So I think the "See Also" links are too buried -- this is where people can view the items online which should be a prominent feature. Example records are http://biblia-arabica.com/bibl/110 (Google Books) and http://biblia-arabica.com/bibl/475 (Archive.org) though there are other repositories we sometimes link to as well.

If it's not too hard, it would be nice to have a button similar to the "Corrections/Additions" button that says "View at [website]" when there is a See Also link other than Zotero.org or Worldcat.org. The text of the button could be determined by the domain, e.g., 
```
for $x in //(idno|ref/@target)[not(matches(.,'(http://biblia-arabica.com|https://zotero.org|http://www.worldcat.org)'))]
replace($x,'https?://(.*?)/.*','$1')
```
or whatever better code you come up with for "View at Archive.org" etc.

The button could be placed next to the See Also link or wherever else you think it goes nicely. Note that there may sometimes be multiple buttons.

Now I'm really stretching, but it would be fantastic if the button also appeared in the short view of browse and search lists.

**Comment by wsalesky** [comment]
@nathangibson Would you want this in the right hand menu? Or do you want it embedded in the page?

**Comment by wsalesky** [comment]
Branch issue20 has buttons added to the right hand menu. I'm not entirely sure this is optimal. I will see what else I can come up with.

**Comment by nathangibson** [comment]
Thanks, you did this fast! I would love for it to be even more obvious--one of the first things you see. What about using one of those blue accent buttons like I've seen somewhere on Syriaca? And perhaps putting it just above or just below the preferred citation box?

**Comment by wsalesky** [comment]
@nathangibson I moved it to the center, shall I move it to the server version?

**Comment by nathangibson** [comment]
Yes please.

**Comment by wsalesky** [comment]
Done.
