### ISSUE TITLE
Change keyboard language selections

### ISSUE THREAD

**Issue by nathangibson** [biblia-arabica/srophe-eXist-app#22]
Perhaps this is something I can do if I get time. 

We would like 
Arabic Mod. Standard
Hebrew
English QWERTY

**Comment by wsalesky** [comment]
It is supposed to be fairly straight forward, you need to make sure there is a link on templates/page.html to the correct language (I think you have to add Hebrew, the others are already there) and then add Hebrew to the repo.xml file as well (the id can be found at the top of the specified language's javascript code). 

Let me know if that does not work, or is to convoluted.

**Comment by wsalesky** [comment]
Done.
