### ISSUE TITLE
Faster browse/search results. 

### ISSUE THREAD

**Issue by wsalesky** [biblia-arabica/srophe-eXist-app#28]
This will require fewer xslt template calls.

**Comment by wsalesky** [comment]
@nathangibson I moved the citation formatting to xquery rather then XSLT, it seems much faster. Let me know if there are any display issues, the citation XSLTs are rather convoluted so I may have missed some things. However the browse and search pages are quite a bit speedier.

**Comment by nathangibson** [comment]
Wow, this is now lightning fast. Thanks!

**Comment by wsalesky** [comment]
Great! Thanks, I'm porting this change over to Syriaca.org as well, so we should see s bump in speed there soon.
