### ISSUE TITLE
Custom page references in Zotero notes

### ISSUE THREAD

**Issue by nathangibson** [biblia-arabica/srophe-eXist-app#3]
When a bibliographic item is an entire book, and we want to refer to certain pages in it as relevant to our bibliography (but not as a "book section" item type) there is no place to put the pages in Zotero.

What we have done for now is to add a note beginning with "PP: " and then list the pages. E.g., https://www.zotero.org/groups/538215/biblia_arabica/items/itemKey/6BVBAQGI has a note "PP: 13, 23, 67-69, 73, 133-138, 148-162, 173-184 and 208-212". 

We need to include this as a citedRange in the export to TEI. 

And is this an OK place to put the pages or should we put them somewhere else? 

A possible advanced feature: Our original bibliography referred to certain page ranges for certain subjects. So a single item might list multiple page ranges, each for a different subject. E.g., https://www.zotero.org/groups/538215/biblia_arabica/items/itemKey/NMV2SFG9. In the TEI this could perhaps be multiple citedRanges with a corresp or ana attribute pointing to the subject or subject URI. In the HTML it could list the subject name beside the page range in parentheses. If this is complicated we should split it into a separate issue and see if we have time for it later.

**Comment by wsalesky** [comment]
See data branch. (Still need to do the second half, i.e. break out cited ranges referencing subjects.)

**Comment by nathangibson** [comment]
We are interested in this feature eventually, but it is not the highest priority for the demo, so feel free to leave it aside if there are others that still need work. Thanks!

**Comment by wsalesky** [comment]
@nathangibson I noticed the notes field is not output by the api when I request the JSON, looking for a way to grab those as well, and then I will add the additional cited ranges to the zotero2bibl transform and the HTML output.

**Comment by nathangibson** [comment]
Hmm, that's weird. I don't know if it's any help but the `&include=bib` parameter does output the content of note items and links them to their parent item using `links.up.href`.

**Comment by wsalesky** [comment]
@nathangibson That's embarrassing! It is a leftover error processing message in the Zotero transformation. I have removed it, but you will have to rerun the records.

**Comment by nathangibson** [comment]
No problem!

**Comment by nathangibson** [comment]
Currently  this looks like "CitedRange: 67" (e.g., http://lmkwitg-xdb01.srv.mwn.de/exist/apps/ba-dev/bibl/4DKA9SGQ). 
I want to change this to "See pp. 67" and move it farther up the page.

**Comment by nathangibson** [comment]
This is still not showing up, e.g., for https://biblia-arabica.com/bibl/N6J9N2WK = https://www.zotero.org/groups/538215/biblia_arabica/items/itemKey/N6J9N2WK

**Comment by wsalesky** [comment]
@nathangibson checking back in on this. Where on the page would you like this to appear?

**Comment by wsalesky** [comment]
@nathangibson on a new line?

**Comment by wsalesky** [comment]
Added. Will need to rerun the data for the pages to be included. 
Also I noticed duplication in this record: https://www.zotero.org/groups/538215/biblia_arabica/items/itemKey/N6J9N2WK

I was using it to test. That means the pages show up twice. See: 
<img width="910" alt="screen shot 2018-12-18 at 2 19 48 pm" src="https://user-images.githubusercontent.com/1168206/50177449-0a411000-02d0-11e9-8365-47bc085e4ed1.png">
