### ISSUE TITLE
Add Hebrew to browse tab languages

### ISSUE THREAD

**Issue by nathangibson** [biblia-arabica/srophe-eXist-app#32]
At http://lmkwitg-xdb01.srv.mwn.de/exist/apps/ba/bibl/browse.html?view=A-Z
The character range is א [U+05D0] to ת [U+05EA] and the tab label should be "א-ת". This should come between Arabic and "Other."

**Comment by wsalesky** [comment]
Added. Do you want an 'abc' menu along the top as well? Like English and Arabic? Or is it fine as is? So far there are not many records, so splitting them up under letter menus does not make as much sense, but you may have a lot of them in the future.

**Comment by nathangibson** [comment]
Thanks! I think in future there will probably be enough to warrant the 'abc' menu, but I am moving that to stage 2. Below is one letter per line, in order.

א
ב
ג
ד
ה
ו
ז
ח
ט
י
כ
ל
מ
נ
ס
ע
פ
צ
ק
ר
ש
ת

**Comment by nathangibson** [comment]
Individual letters possibly obselete in light of #52 . Close issue?

**Comment by wsalesky** [comment]
Sounds good.
