### ISSUE TITLE
Advanced Browse sorting

### ISSUE THREAD

**Issue by nathangibson** [biblia-arabica/srophe-eXist-app#34]
The title sort order at browse.html?view=facets is different from browse.html?view=A-Z. I like the second better as it eliminates punctuation, numbers, and blank titles, which appear at the beginning of the list in the advanced browse.

**Comment by wsalesky** [comment]
@nathangibson The title sort for the Alphabetical filters on the first letter of the title, so all blank and numeric titles are not actually in the list. The advanced browse is doing a sort on all titles (no letter filter applied). I can filter out blank titles, but I would not think we would want to filter out numbers? Those would then not appear anywhere in the browse.

**Comment by nathangibson** [comment]
Appears fixed.
