### ISSUE TITLE
Correct Zotero URIs

### ISSUE THREAD

**Issue by nathangibson** [biblia-arabica/srophe-eXist-app#36]
Something weird is happening with the Zotero URIs. I think this is left over from how I originally wrote the TEI transform. 

E.g., http://biblia-arabica.com/bibl/CW4DTAC2 displays the following:

> Zotero: https://www.zotero.org/groups/biblia_arabica/items/CW4DTAC2
> URI: https://api.zotero.org/groups/538215/items/CW4DTAC2

The first is an idno with type="zotero" but should be type="URI". And I wonder if we should strip out the "api" subdomain of the second? I'm not sure it makes sense to send regular users to a JSON page, and advanced users will know enough to be able to get to the Zotero API. So should we just do https://zotero.org/groups/538215/items/CW4DTAC2 for the second link? What do you think?

**Comment by wsalesky** [comment]
@nathangibson I think the a single link to the Zotero record is probably fine. I will switch the type for the first to URI and swap out the api subdomain so the links look like this: 

> URI: https://www.zotero.org/groups/biblia_arabica/items/CW4DTAC2
> URI: https://www.zotero.org/groups/538215/items/CW4DTAC2

**Comment by wsalesky** [comment]
Done in the data, the change needs to be merged into master if it looks good to you. I will move it to the server after it has been merged.

**Comment by nathangibson** [comment]
Looks good, thanks!
