### ISSUE TITLE
Add record creator to TEI using Zotero data

### ISSUE THREAD

**Issue by nathangibson** [biblia-arabica/srophe-eXist-app#37]
We would like to show credit, to the extent possible, for the people who worked on each bibliography entry. I don't see that Zotero records everyone who worked on a record, only the creator and the last editor. So I would suggest the following and welcome your input: 

1. Add the following to the TEI record at /TEI/teiHeader/titleStmt, where [userURI] is `meta.createdByUser.links.alternate.href` and [username] is `meta.createdByUser.name` with a fallback to `meta.createdByUser.username`.
`<editor role="creator" ref="[userURI]">[username]</editor>`
as well as 
 `<respStmt><resp>Record added to Zotero by</resp><name ref="[userURI]">[username]</name></respStmt>`
2. Also add lastModifiedByUser if present, where [userURI] is `meta.lastModifiedByUser.links.alternate.href` and [username] is `meta.lastModifiedByUser.name` with a fallback to `meta.lastModifiedByUser.username`.
`<editor role="creator" ref="[userURI]">[username]</editor>`
as well as 
 `<respStmt><resp>Record edited in Zotero by</resp><name ref="[userURI]">[username]</name></respStmt>`
3. We are using tags beginning with "Assigned: " to designate who does additional editing on records. If we made this match our Zotero user ids could we add the following too (if different from the above editors)? 
`<editor role="creator" ref="[userURI]">[username]</editor>`
and
 `<respStmt><resp>Primary editing by</resp><name ref="[userURI]">[username]</name></respStmt>`
E.g., https://www.zotero.org/groups/538215/biblia_arabica/items/itemKey/UM5WDKIF has the tag "Assigned: nathanpgibson". This would be parsed as 
`<editor role="creator" ref=""https://www.zotero.org/nathanpgibson"">Nathan P. Gibson</editor>`
and
 `<respStmt><resp>Primary editing by</resp><name ref=""https://www.zotero.org/nathanpgibson"">Nathan P. Gibson</name></respStmt>`

**Comment by wsalesky** [comment]
Added to the data.
