### ISSUE TITLE
Additions to advanced search

### ISSUE THREAD

**Issue by nathangibson** [biblia-arabica/srophe-eXist-app#38]
We would like to add the following to advanced search
- Date as range instead of single field (like http://wwwb.library.vanderbilt.edu/persons/search.html) 
- Subject (for now a text search of `/TEI/text/body/listRelation/relation[@ref='dc:subject']/desc` though in future should it be powered by the passive URI?)
- Manuscript (for now a text search of `/TEI/text/body/listRelation/relation[@ref='dcterms:references']/desc/bibl`. I will make a separate issue for some more complicated logic for manuscripts in [Stage 2](https://github.com/biblia-arabica/srophe-eXist-app/milestone/2))
- ISBN / DOI / URI as identifier searches
- "Only items viewable online" with checkbox

**Comment by wsalesky** [comment]
@nathangibson Please review and close if the changes look correct.

**Comment by nathangibson** [comment]
Looks good!

Could we have a drop-down of existing subjects for the subject field?

**Comment by wsalesky** [comment]
Added subject drop down. Subjects sorted alphabetically.
