### ISSUE TITLE
Decide how to handle subject tagging

### ISSUE THREAD

**Issue by nathangibson** [biblia-arabica/srophe-eXist-app#4]
Right now, subjects are tagged in Zotero with tags in the format "Subject: " (e.g., https://www.zotero.org/groups/538215/biblia_arabica/items/itemKey/NMV2SFG9). 

Should we use URIs for subject tagging? This could include using Syriaca/Srophe taxonomy module (or simply having them add the subjects we need) as well as tagging people and works. I'm not sure how developed this feature is currently in the bibliography module, so I'm essentially asking what would be less work on your end.

The alternative would be to rigidly maintain the standardization of the text-string subject tags. 

You will notice that right now there are some hierarchical subjects, marked as "Subject: Part One: Historic Printings: Spey (1583)". I don't imagine we will keep these this way -- I think we will eventually use multiple tags instead so you can ignore this hierarchy for now.

**Comment by wsalesky** [comment]
Resolved here: 
https://github.com/biblia-arabica/srophe-eXist-app/issues/2

**Comment by wsalesky** [comment]
@nathangibson I am comparing the new output with the old, and I'm noticing some records had subjects and no longer do. Examples: 
http://lmkwitg-xdb01.srv.mwn.de/exist/apps/ba/bibl/476
https://www.zotero.org/groups/538215/biblia_arabica/items/itemKey/2RDD2JA4/q/Acta%20mythologica%20Apostolorum

The Zotero link has no subject tags? Have you been doing some editing, or am I missing something. 
Thanks.

**Comment by nathangibson** [comment]
I have been doing some editing, including on the example you cited. I don't remember exactly what I did but I think it is fine. Thanks!

**Comment by wsalesky** [comment]
This has also been taken care of.
