### ISSUE TITLE
Advanced Browse sorting

### ISSUE THREAD

**Issue by nathangibson** [biblia-arabica/srophe-eXist-app#41]
I'm out of time for today, but I want to discuss how we can consolidate/improve the sorting options for browse and advanced browse in terms of languages and sort parameters (title and author). I will try to fill out this issue later.

**Comment by wsalesky** [comment]
@nathangibson This is the last issue in Stage 1. If you give me details I can have finish up with all stage 1 developments this week.

**Comment by wsalesky** [comment]
@nathangibson Checking in on this ticket.

**Comment by nathangibson** [comment]
OK, sorry this has taken so long to get back to you! 

Can we simply disregard punctuation and numbers for advanced browse sorting? Currently I am seeing the following items show at the beginning of the list: ¿ ... ' ( [ 

So the following would show up under "C" for example: 
¿Circularon textos cristianos orientales en al-Andalus? Nuevos datos a partir de una muestra véterotestamentaria andalusí 

I think this is all we need, since items without a title are ones we should resolve in the data anyway.

This also addresses #34 .

**Comment by nathangibson** [comment]
This appears fixed to me. Feel free to close.
