### ISSUE TITLE
Enhanced citation options

### ISSUE THREAD

**Issue by nathangibson** [biblia-arabica/srophe-eXist-app#44]
We are interested in the following citation options, but do not want to slow down your now lighting-fast load times. Let me know what sounds feasible. 
 1. Would it be possible to include on the record page the metadata (=COINS format?) that will allow the user's Zotero plugin to recognize and import the item? E.g. https://api.zotero.org/groups/538215/items/R9NJSR5Q?format=coins. This is most important on the record detail page but would also be convenient on the advanced browse/search results pages if it doesn't slow them down too much. 
 2. What about including a drop-down that allows you to choose different citation styles and copy the result, like what you get if you click on the second button in the screenshot below at https://www.zotero.org/groups/538215/biblia_arabica/items/itemKey/R9NJSR5Q ? Perhaps this could be generated on demand so as not to slow load times by constructing links such as https://api.zotero.org/groups/538215/items/R9NJSR5Q?format=bib&style=chicago-note-bibliography.
 3. Speaking of citation styles generated by Zotero, rather than you having to continue the xQuery madness of formatting citations, would it make more sense to pull the Zotero formatted citation (in a default style such as chicago-note-bibliography into the TEI file and display it that way? 
 4. Finally, I wonder if we should link directly (or via a drop-down) to any of the formats surfaced by the first button in the screenshot below. Thoughts?

![zotero___groups___biblia_arabica___library___the_persian_and_arabic_gospel_harmonies](https://user-images.githubusercontent.com/3083452/33078067-e35a22c0-ced1-11e7-96c0-00c0f9358392.png)

**Comment by nathangibson** [comment]
I'm still wondering what might be possible here ...

**Comment by wsalesky** [comment]
@nathangibson It looks like there is an api for this. Example: https://api.zotero.org/groups/538215/items/N6J9N2WK?format=bib&style=apa

or 
https://api.zotero.org/groups/538215/items/N6J9N2WK?format=bib&style=chicago-author-date-basque

We would have to do some research to decide what styles you want to make available and then just make a request to the API. Should be fairly easy. To demo I will just use the default options. Should have something for you to look at tomorrow afternoon.

**Comment by wsalesky** [comment]
@nathangibson I added a button for the citation styles. We can still investigate the export function. Looks like that can also be done using the Zotero API. However I am running low on time so perhaps we can leave this issue open for now and come back to it?

**Comment by wsalesky** [comment]
@nathangibson I think this is complete? Please let me know if I missed something.
