### ISSUE TITLE
Add corrections/additions button

### ISSUE THREAD

**Issue by nathangibson** [biblia-arabica/srophe-eXist-app#48]
Like Syriaca.org

**Comment by wsalesky** [comment]
I will need your SMT server address. Also what addresses should corrections/additions be sent to?

**Comment by nathangibson** [comment]
Update: When loading any item detail page (e.g., http://lmkwitg-xdb01.srv.mwn.de/exist/apps/ba/bibl/2V4AQWB4), I get a message saying in German the equivalent of "reCaptcha cannot be reached. Check the connection and try again."

**Comment by nathangibson** [comment]
Now I get the error message "invalid domain for website key" (in German). Will this be automatically fixed when we move to the biblia-arabica.com domain?

**Comment by wsalesky** [comment]
@nathangibson what domain do you have for registered for reCaptcha? (You could register both, then it will not be a problem.)

**Comment by nathangibson** [comment]
I have both biblia-arabica.com and lmkwitg-xdb01.srv.mwn.de registered. I don't need to list http or https in front of them, do I?

**Comment by wsalesky** [comment]
This should be fixed. (I sent a test email, close if you received it)

**Comment by wsalesky** [comment]
@nathangibson Yes, I think that will fix the issue. If not let me know.

**Comment by wsalesky** [comment]
@nathangibson did that commit fix the issue?

**Comment by nathangibson** [comment]
Unfortunately this isn't fixed with the new version. (You can test now on the biblia-arabica.com server.)

There is no feedback/response when I click the "Send e-mail" button on the form. 

The Post request gets a 400 error. See screenshot for details.
![al-alam_s_version_of_zechariah](https://user-images.githubusercontent.com/3083452/48428126-9a88b400-e76a-11e8-948b-3abda147a169.jpg)

**Comment by wsalesky** [comment]
@nathangibson I think this is fixed?
