### ISSUE TITLE
Add advanced browse for bibliography

### ISSUE THREAD

**Issue by nathangibson** [biblia-arabica/srophe-eXist-app#5]
We would like a faceted browse such as http://wwwb.library.vanderbilt.edu/exist/apps/srophe/persons/browse.html?view=facets for bibliography.

Some suggested initial facets to try:
 - Publication Date (//biblStruct/*/imprint/date)
 - Subjects (Have we designated a place for this yet in the Syriaca biblStruct format?)
 - Manuscripts

**Comment by wsalesky** [comment]
For publication dates do you want to do a range (maybe by decade) or individual dates?

**Comment by nathangibson** [comment]
Let's try a range by decade.

**Comment by wsalesky** [comment]
Starting and ending where(ish)

**Comment by nathangibson** [comment]
Well, I was going to say 1470 to present but that would be a lot! Maybe we should do 50-year ranges?

**Comment by wsalesky** [comment]
Okay, It is easily adjustable, I tried Century, but the current values are all clustered in the 1800-2000 (although looking at the numbers there may be some data missing).

**Comment by nathangibson** [comment]
Thanks. I'm sure we will be able to tell you better once we have an example to look at but I think the 50-years is OK for now.

**Comment by wsalesky** [comment]
Code is in place. I added a branch to the data repository with updated data (I ran a few xqueries to get the data in the correct format). In the future this data will be output via the Zotero script, but rather then waiting for it to be ready we can fake it for now. 

Data branch: 
https://github.com/biblia-arabica/biblia-arabica-data/tree/issue3

**Comment by nathangibson** [comment]
Would be awesome if we could add another facet to Advanced Browse that is a simple toggle "Viewable Online". With the current structure this could be a "Viewable Online" header with "Yes" and "No" values. The logic would be bibls that have idnos or ref targets that are not biblia-arabica.com, https://zotero.org, or http://www.worldcat.org

**Comment by wsalesky** [comment]
Still need to make it a toggle, not a button like all the rest.

**Comment by nathangibson** [comment]
I have run the advanced browse options through the academic committee, and we have come up with the following additional facets/tweaks:

- Please sort Publication Date from newest to oldest (reverse of now).
- At 1900 and above, how difficult would it be to break it into 25-year ranges? 
- Can we add a facet for "Authors/Contributors" ? Names should be "[surname], [forename]". This would facet on `/TEI/text/body/biblStruct/*/(author|editor)` -- in other words any contributor in any level of the bibliography item.
- Can we reorder the facets to be "Subjects", "Authors/Contributors", "Manuscripts", "Publication Date", "Viewable Online" ?

We might have some more tweaks -- I will need to take another look at my notes. Thanks!

**Comment by wsalesky** [comment]
Done. Let me know if there is anything else you need.

**Comment by nathangibson** [comment]
Thanks!
