### ISSUE TITLE
Consolidate Advanced Browse

### ISSUE THREAD

**Issue by nathangibson** [biblia-arabica/srophe-eXist-app#52]
Priority no. 2 for Stage 2

We feel that Advanced Browse should be *the* interface for exploring the bibliography. As such, we would like to consolidate what happens when you click on the "Browse" button. 

Instead of having Advanced Browse as one of several tabs, could we remove the "Advanced Browse" label and have the different script options ("A-Z" etc.) as subtabs *within* the advanced browse page?

**Comment by wsalesky** [comment]
Let me know what you think: http://lmkwitg-xdb01.srv.mwn.de/exist/apps/ba/bibl/browse.html?view=A-Z

**Comment by nathangibson** [comment]
Visually I find this makes more sense than earlier. However, I'm realizing that the filtering logic is complex and doesn't end up with the user being able to do what I intended. Sorry this is my problem not yours!

Right now, it looks as if the filtering is in this order: Script > Letter > Facet > Page number. There are some problems with this from a user perspective. 1) Users would want to facet before they page through letters, but right now the faceting is for each individual letter. So you have to select "Generalia" for A, then click on B and select "Generalia" again, and so on. And because the facets are based on the tags of the current letter, the one you're looking for might not even appear. 2) The letter paging doesn't really make sense if one is sorting by date. 

My suggestion below is a bit radical ... I'm open to other ideas....
I wouldn't think of the scripts and letters as filtering but rather as a paging device, so that if someone is looking for a particular author or title, they can find it in the right spot (after faceting, if applicable). So what if instead of having a letter and then a pager for each letter, the pagers grabbed the first 3 letters of the part of the title/author string being sorted on for the 1st and last items on the page, and displayed these instead of the alphabet? E.g., "Abb-And", "And-Ara", "Ara-Ara", "Ara-Aut", and so on down to "Von-Zur". I realize these labels would have to be auto-generated, so is that quite tricky? 
Then the script tabs would function not as a filter in the true sense, but as a way to access the pagers for that script. Essentially the whole bibliography with all scripts would function as one big long list (with A-Z followed by ا-ي, then א-ת, then Other), and then the facets would also function properly. 

When sorted by date, you would have as pagers, e.g., 1516-1612, etc.

Thoughts? Other suggestions?

Overall, I would say what is most important is that the facets work across the entire bibliography.

**Comment by wsalesky** [comment]
That make sense. It will require some reworking of the xquery that powers the browse. I will let you know when I have something working.

**Comment by wsalesky** [comment]
Okay, this should be closer. At least there is a working advanced browse. Bells and whistles can be added later. 

This does not have the  fancy paging mentioned above (not enough coding time left), perhaps we can revisit it as a future enhancement.

**Comment by nathangibson** [comment]
Sounds good! I think this is much more functional now.

**Comment by nathangibson** [comment]
Future tweaks should include fixing "Sort by" which for "Title" is somehow different from the default sort and for other sorting options doesn't seem to do anything.

**Comment by wsalesky** [comment]
This is better, there are issues with dates as they are not all uniformly entered. I think that is a data issue though, not a script issue.

**Comment by nathangibson** [comment]
Ahh, yes, this is definitely better but will need some more tweaking and data cleanup.
