### ISSUE TITLE
"Browse" link in header sometimes links to browse.html?view=A-Z instead of browse.html

### ISSUE THREAD

**Issue by nathangibson** [biblia-arabica/srophe-eXist-app#60]
On some pages such as http://lmkwitg-xdb01.srv.mwn.de/exist/apps/ba/bibl/index.html and item detail pages like http://lmkwitg-xdb01.srv.mwn.de/exist/apps/ba/bibl/2V4AQWB4 the "Browse" link in the header links to browse.html?view=A-Z, which is no longer the correct syntax after #52 and shows only 99 results.

**Comment by nathangibson** [comment]
I might be able to fix this.

**Comment by wsalesky** [comment]
I suspect caching

**Comment by nathangibson** [comment]
Oops, sorry!

**Comment by wsalesky** [comment]
👍
