### ISSUE TITLE
Add copy button to preferred citation

### ISSUE THREAD

**Issue by nathangibson** [biblia-arabica/srophe-eXist-app#64]
To add sometime ...

Some websites (such as https://www.gesundheit.de/ernaehrung/alles-bio) add extra text to the clipboard to identify the citation when you copy something. We might want to look at doing this for Biblia Arabica. E.g., "Cited from http://biblia-arabica.com/...".

**Comment by nathangibson** [comment]
Making this more general -- it would be good to have a copy button (like the URI copy button) for the preferred citation. 
As mentioned above, this could add to the end of the citation "Cited from [URI]."

**Comment by wsalesky** [comment]
Done.
