### ISSUE TITLE
Error on eXist landing pages 

### ISSUE THREAD

**Issue by nathangibson** [biblia-arabica/srophe-eXist-app#65]
I get an eXist error when I go to http://lmkwitg-xdb01.srv.mwn.de/exist/apps/ba/bibl/index.html and a 404 when I go to http://lmkwitg-xdb01.srv.mwn.de/bibl/browse.html and http://lmkwitg-xdb01.srv.mwn.de/bibl/index.html. 

Is this a problem with eXist settings or something our server admin needs to solve?

```
exerr:ERROR XPTY0004: The actual cardinality for parameter 2 does not match the cardinality declared in the function's signature: replace($input as xs:string?, $pattern as xs:string, $replacement as xs:string) xs:string?. Expected cardinality: exactly one, got 0. [at line 625, column 26, source: /db/apps/ba/modules/lib/global.xqm]
In function:
	app:dashboard(node(), map, item()*, item()*) [221:18:/db/apps/ba/modules/app.xql]
	templates:call-with-args(function, function*, element(), map) [208:13:/opt/exist/./webapp/WEB-INF/data/expathrepo/shared-0.4.2/content/templates.xql]
...
```

**Comment by wsalesky** [comment]
Fixed. Needed to retrigger a webhook to push new repo-config.xml file to the server. 

To get the short paths working  (http://lmkwitg-xdb01.srv.mwn.de/bibl/browse.html) you will need to have your system admin get Apache or  NGINX to set the webroot to http://lmkwitg-xdb01.srv.mwn.de/exist/apps/ba/

Thanks!

**Comment by nathangibson** [comment]
Thanks!
