### ISSUE TITLE
Preferred citation formatting

### ISSUE THREAD

**Issue by nathangibson** [biblia-arabica/srophe-eXist-app#67]
There are numerous issues (commas, spaces, etc.) with formatting of the "Preferred Citation" and the citation on the brief browse/search view. We could address these individually, but I wonder if the easiest thing would be to simply import the Chicago citation through the Zotero API? (See https://github.com/biblia-arabica/srophe-eXist-app/issues/44). Let me know if you prefer that I list the individual issues.

**Comment by wsalesky** [comment]
@nathangibson it is up to you if you, but development time wise it would probably be fastest to import the Zotero citation. Maybe as a new note field? We can also try importing the latest from Syriaca.org, see if that helps at all.

**Comment by nathangibson** [comment]
I definitely think it is best to import the formatted citation from Zotero. Citation style is Zotero's specialty, and if we are writing our own transform we are bound to get it wrong somewhere. 

I would suggest adding a typed bibl element after the biblStruct, like so ( for https://www.zotero.org/groups/538215/biblia_arabica/items/itemKey/2B7SK2Y7)
```
<bibl type="formatted" subtype="http://www.zotero.org/styles/chicago-note-bibliography-16th-edition">
                Schnurrer, Christian Friedrich. <hi rend="italic">Dissertatio de Pentateucho Arabico Polyglotto Disputatio Philologica</hi>. T&#xFC;bingen, 1780.
            </bibl>
```
What do you think? Is there some way note would be better? 

As you see, italics would have to be converted from HTML to TEI. 

This would also allow us to add other citation styles from Zotero if we want.

Let me know if you feel you have time or if I should attempt this in https://github.com/biblia-arabica/zotero2bibl/blob/master/zotero2tei.xqm.

**Comment by wsalesky** [comment]
@nathangibson That sounds good. I will have time in 2 weeks to add this, if you want to try before then that is fine. See https://github.com/biblia-arabica/zotero2bibl/blob/master/zotero2tei.xqm#L302 for how we make an additional call for each record to get the notes. The citation would be similar.

**Comment by nathangibson** [comment]
OK, thanks!

**Comment by nathangibson** [comment]
@wsalesky I'm working on this since we are trying to do a soft launch very, very soon. Right now one of the biggest issues I see is that many citations are just not turning out correctly. 

This is what I'm trying to do to import the formatted Zotero citation:
https://github.com/biblia-arabica/zotero2bibl/commit/96d0397cddc17d7e63e86d05109d4a092504843e
Zotero's JSON API has an include=bib parameter, so I thought we could just call that when loading the data initially. Does this approach seem sensible? (It doesn't yet strip out the HTML and replace italics with TEI formatting.)

**Comment by wsalesky** [comment]
@nathangibson Yes that seems reasonable. Can you run it on a subset of the data to get an idea of how it supposed to work? When is the soft launch, I can see if I can solve this issue: https://github.com/biblia-arabica/zotero2bibl/issues/13 so you can test locally on a subset of records.  May take an hour or 2.

**Comment by nathangibson** [comment]
Thanks! Ideally next week, though I'm not sure whether we'll have the data ready yet by then.

**Comment by nathangibson** [comment]
That is very kind! I think the main thing is I'm still trying to make some tweaks in the Zotero conversion and might need some guidance or troubleshooting there. 

One thing I'm thinking of is using the suggestion here to batch find-replace some Zotero data:
https://forums.zotero.org/discussion/comment/112198/#Comment_112198

What do you think?

**Comment by nathangibson** [comment]
On another note, our server is kind-of back up and running. (Everything seems to be working except Dashboard, strange.) And the get-zotero-data requests are now working. Yay!
So I was able to process a batch of 100 records, and they are successfully pulling in the formatted citations. See list below. Example: http://lmkwitg-xdb01.srv.mwn.de/exist/apps/ba-dev/bibl/SYDH8BVT where the citation renders as a bullet point. 
I think I can handle stripping out the HTML and replacing italics with TEI italics. But I'm not too confident about being able to cleanly tell the XSLT to insert this formatted citation in the "Preferred Citation" box. 

/db/apps/ba-data-dev/data/bibl/tei/SYDH8BVT.xml /db/apps/ba-data-dev/data/bibl/tei/LWX8DSZZ.xml /db/apps/ba-data-dev/data/bibl/tei/SCB9S6UV.xml /db/apps/ba-data-dev/data/bibl/tei/SNAWNPV6.xml /db/apps/ba-data-dev/data/bibl/tei/V45RWQAR.xml /db/apps/ba-data-dev/data/bibl/tei/3KICPIPH.xml /db/apps/ba-data-dev/data/bibl/tei/S3W6RCJE.xml /db/apps/ba-data-dev/data/bibl/tei/EID7GMAY.xml /db/apps/ba-data-dev/data/bibl/tei/BPM9PSNS.xml /db/apps/ba-data-dev/data/bibl/tei/TTZ5KMAI.xml /db/apps/ba-data-dev/data/bibl/tei/9QTP86HD.xml /db/apps/ba-data-dev/data/bibl/tei/MR2EY82Y.xml /db/apps/ba-data-dev/data/bibl/tei/Y48QHQDJ.xml /db/apps/ba-data-dev/data/bibl/tei/EK2ZXBV3.xml /db/apps/ba-data-dev/data/bibl/tei/3U7KH8T5.xml /db/apps/ba-data-dev/data/bibl/tei/KVLTTZDD.xml /db/apps/ba-data-dev/data/bibl/tei/FHMZ3DAK.xml /db/apps/ba-data-dev/data/bibl/tei/PRQ7GPCU.xml /db/apps/ba-data-dev/data/bibl/tei/UGFPG5C7.xml /db/apps/ba-data-dev/data/bibl/tei/7VX8JXVR.xml /db/apps/ba-data-dev/data/bibl/tei/MJSIR68P.xml /db/apps/ba-data-dev/data/bibl/tei/DRA89TUY.xml /db/apps/ba-data-dev/data/bibl/tei/W6KW2WTD.xml /db/apps/ba-data-dev/data/bibl/tei/DCYG7XEE.xml /db/apps/ba-data-dev/data/bibl/tei/FQXVXAQV.xml /db/apps/ba-data-dev/data/bibl/tei/RCEKSETS.xml /db/apps/ba-data-dev/data/bibl/tei/BUWPZXG6.xml /db/apps/ba-data-dev/data/bibl/tei/PMMVBDEB.xml /db/apps/ba-data-dev/data/bibl/tei/6K6QAZTZ.xml /db/apps/ba-data-dev/data/bibl/tei/SABFBYFY.xml /db/apps/ba-data-dev/data/bibl/tei/3R3ZY84N.xml /db/apps/ba-data-dev/data/bibl/tei/IU2CVCW2.xml /db/apps/ba-data-dev/data/bibl/tei/VU26GACI.xml /db/apps/ba-data-dev/data/bibl/tei/CTZ9A3K7.xml /db/apps/ba-data-dev/data/bibl/tei/YFTEZH78.xml /db/apps/ba-data-dev/data/bibl/tei/ESAC7NZV.xml /db/apps/ba-data-dev/data/bibl/tei/ZKMMS92H.xml /db/apps/ba-data-dev/data/bibl/tei/NRX6HKHH.xml /db/apps/ba-data-dev/data/bibl/tei/TKUWTBG9.xml /db/apps/ba-data-dev/data/bibl/tei/554Q2HNI.xml /db/apps/ba-data-dev/data/bibl/tei/7AJ75QEK.xml /db/apps/ba-data-dev/data/bibl/tei/85QZWRQI.xml /db/apps/ba-data-dev/data/bibl/tei/46V5V4BC.xml /db/apps/ba-data-dev/data/bibl/tei/T599VRN3.xml /db/apps/ba-data-dev/data/bibl/tei/ES5JYELJ.xml /db/apps/ba-data-dev/data/bibl/tei/ANMISVR9.xml /db/apps/ba-data-dev/data/bibl/tei/NUSR5HWK.xml /db/apps/ba-data-dev/data/bibl/tei/EIZ372IW.xml /db/apps/ba-data-dev/data/bibl/tei/URYH7KF7.xml /db/apps/ba-data-dev/data/bibl/tei/G38R46KP.xml /db/apps/ba-data-dev/data/bibl/tei/GHSFYK59.xml /db/apps/ba-data-dev/data/bibl/tei/J8MTXEYF.xml /db/apps/ba-data-dev/data/bibl/tei/BFWVWGSC.xml /db/apps/ba-data-dev/data/bibl/tei/FLXNPKWL.xml /db/apps/ba-data-dev/data/bibl/tei/HWBG3XQW.xml /db/apps/ba-data-dev/data/bibl/tei/IYH9K4AC.xml /db/apps/ba-data-dev/data/bibl/tei/L98CR629.xml /db/apps/ba-data-dev/data/bibl/tei/N23AB6P5.xml /db/apps/ba-data-dev/data/bibl/tei/M7HINYJ5.xml /db/apps/ba-data-dev/data/bibl/tei/KIT3BSQ5.xml /db/apps/ba-data-dev/data/bibl/tei/XVG6IP84.xml /db/apps/ba-data-dev/data/bibl/tei/HBVXFAXL.xml /db/apps/ba-data-dev/data/bibl/tei/7KUWFFG9.xml /db/apps/ba-data-dev/data/bibl/tei/AITBEPUE.xml /db/apps/ba-data-dev/data/bibl/tei/QS88BFY7.xml /db/apps/ba-data-dev/data/bibl/tei/VIXCUIRI.xml /db/apps/ba-data-dev/data/bibl/tei/7BFF2G7K.xml /db/apps/ba-data-dev/data/bibl/tei/U2XGC4W9.xml /db/apps/ba-data-dev/data/bibl/tei/ZM7HRFH6.xml /db/apps/ba-data-dev/data/bibl/tei/NWSUXX8R.xml

**Comment by wsalesky** [comment]
@nathangibson I may be able to help if you give me an example file that is not working. Have you tried: parse-xml-fragment() ? this may make it easier to strip unwanted HTML. 

Also, I noticed when I looked at a test record that some of them still have the 'Hey, this one has kids!' Which I had added to troubleshoot, but I thought we had fixed in a past version. 

It is no longer in the code: https://github.com/biblia-arabica/zotero2bibl/blob/98753f2ce0cd7b04bfcc063e5e33d52b84504f1e/zotero2tei.xqm#L315

So I wonder if the data file is not being overwritten by the script?

**Comment by nathangibson** [comment]
Yay, parse-xml-fragment worked! I have to make a few more tweaks, but I think I've learned where to do that in the XSLT. I'll use a template for `bibl[@type='formatted']` which will simply italicize `title[@level='m']` and put quotes around `title[@level='a']`.

You can see what I've done so far at http://lmkwitg-xdb01.srv.mwn.de/exist/apps/ba-dev/bibl/EBVWXW94. (The ä in the author name was giving me problems earlier but is now fixed.)

I don't think the troubleshooting message is a problem anymore--it's just that I haven't updated all the records yet.

**Comment by nathangibson** [comment]
I believe this is working correctly now.

**Comment by wsalesky** [comment]
@nathangibson Please take a look. Close if it works as expected.
