### ISSUE TITLE
Fix pub place search field

### ISSUE THREAD

**Issue by nathangibson** [biblia-arabica/srophe-eXist-app#71]
E.g. http://lmkwitg-xdb01.srv.mwn.de/exist/apps/ba-dev/search.html?q=&title=&author=&mss=&pub-place=Leiden&publisher=&start-date=&end-date=&idno= yields 0 results.

**Comment by wsalesky** [comment]
Needed to add tei:pubPlace to collection.xconf. will require a reindex once all the advanced search issues are addressed.

**Comment by nathangibson** [comment]
How do I reindex?

**Comment by wsalesky** [comment]
You can reindex from the dashboard, use the collection browse option, navigate to the data directory where the TEI is, then click the reindex option on the collection browse window.

<img width="776" alt="screen shot 2018-11-13 at 11 47 25 am" src="https://user-images.githubusercontent.com/1168206/48428942-11598900-e73a-11e8-83d6-8ce3eb7de980.png">

**Comment by nathangibson** [comment]
Ahh, great, thanks!
