### ISSUE TITLE
Fix publisher search field 

### ISSUE THREAD

**Issue by nathangibson** [biblia-arabica/srophe-eXist-app#72]
0 results

**Comment by wsalesky** [comment]
@nathangibson Aa an FYI any full text search fields will need to be defined in the Lucene index configuration: (anything in here https://github.com/biblia-arabica/biblia-arabica-data/blob/master/collection.xconf#L6 is part of the Lucene index). The tricky part of this is that this configuration file needs to be added/edited in /db/system/config/db/apps/ba-data/  

When you deploy the data application it saves the collection.xconf file in the correct location, if you are making changes after you have deployed the data repository you will need to either redeploy or edit it manually. I use eXide for this as it then prompts me to re-index when I save the file.

**Comment by wsalesky** [comment]
Needed to add tei:publisher to collection.xconf for indexing.
