### ISSUE TITLE
Expose bibl entries to Zotero Connector

### ISSUE THREAD

**Issue by nathangibson** [biblia-arabica/srophe-eXist-app#81]
It would make sense for users of our bibliography to be able to import items into Zotero directly from our bibl pages instead of having to follow the link to the Zotero group library for each entry. (This means importing the item described, such as a book, rather than importing the page that describes it.) It would especially be useful for lists on the Browse page or in search results. I see three possible ways of doing this. What do you think?

1) Include the coins format in our call to the Zotero API. This could be done here https://github.com/biblia-arabica/zotero2bibl/blob/master/get-zotero-data.xql#L148 as I've done with the formatted citation by replacing `include=bib,data` with `include=bib,data,coins`. 

Then it would be a matter of figuring out where (or whether) to store the coins code in the TEI record. It would be nice if we could do it in a `bibl[@type="coins"]` parallel to the formatted citation `/TEI/text/body/bibl[@type="formatted"]`, but I'm not sure how it could be done in valid TEI. (Except using CDATA, which eXist doesn't seem to like.) And then it would have to be included in the XSLT.

2) Do a separate call when processing the HTML--not storing it in the TEI. The problem with this, besides doing a call each time, is that I suppose it would be inefficient for the search/browse pages.

3) Expose the data to Zotero by converting it from the bibl data. But this seems like asking for trouble if we're manually converting back to Zotero something that was originally in Zotero ... 

Icing on the cake: Include the biblia-arabica.com URI somewhere in the imported record, e.g., as an "attached URI".

**Comment by nathangibson** [comment]
Related: #67

**Comment by nathangibson** [comment]
Hmm, this way of including it in the XML doesn't seem like too much of a hack, does it? 

I like the fact that this would preserve the data in the TEI and therefore also be accessible as part of the dataset that can be copied, manipulated, etc.

On the other hand, in a future version I could see wanting to provide the user with a selection of different citation styles that we pull from Zotero, in addition to being able to import the reference using COINS (see point 2 under #44). Does that mean we will be building a JavaScript loader anyway, and if so would it be more efficient to pull in COINS that way?

Any thoughts, @dlschwartz and @davidamichelson since this is a feature that could be ported to Srophe generally?

**Comment by wsalesky** [comment]
@nathangibson I think the COinS issue is different from the citations issue. COinS you want on the webpage when it loads, the other can be pulled in only when requested. So I would prefer adding it to the TEI and then transforming it in to a COinS object when the HTML is rendered. The other citations can be called by JavaScript via some sort of button or form.

**Comment by nathangibson** [comment]
Great, sounds good!

**Comment by dlschwartz** [comment]
This solution sounds good to me.  @davidamichelson?

**Comment by wsalesky** [comment]
@nathangibson This has been added to the zotero2bibl script and to the HTML generation. Let me know how it works for you.

**Comment by wsalesky** [comment]
@nathangibson I think this can be closed. Reopen if I have missed something.
