### ISSUE TITLE
Add language facet and change "Language" facet to "Citation Script"

### ISSUE THREAD

**Issue by nathangibson** [biblia-arabica/srophe-eXist-app#83]
Our facet currently labeled "Language" is really "Citation Script." Can we label it this and move it to the bottom of the facets?

It would be good to have an actual language facet based on the Language field in Zotero (see https://github.com/biblia-arabica/zotero2bibl/issues/16). 

Not sure where we should store (or grab) the language labels. We are using BCP47 codes with ISO 639 for language and (where notable) ISO 15924 for scripts.

**Comment by wsalesky** [comment]
@nathangibson The first part of this is done. I will add a language facet back in after resolving https://github.com/biblia-arabica/zotero2bibl/issues/16

**Comment by wsalesky** [comment]
Added. Will show up when the data is updated.

**Comment by wsalesky** [comment]
@nathangibson What is the difference between the 'Language' facet and the and the 'Source Language' facet? Is there a way we can label the Language facet that make this more clear?

**Comment by nathangibson** [comment]
Yes, I see your point. I think "Source Language" could be changed to "Translation Source Language" and the language facet you're currently adding could be "Language of Item". What do you think @rvollandt ?

**Comment by wsalesky** [comment]
@nathangibson @rvollandt This is done. There is a list of language codes and matching languages here: https://github.com/biblia-arabica/srophe-eXist-app/blob/master/modules/lib/facet.xqm#L378

New codes will need to be added. Also I did not find the label for 'he-Arab' I can add it if you let me know what it should be. 
Thanks!

**Comment by rvollandt** [comment]
I don’t know the context, but when speaking about translations „Source language“ as a term is pretty clear. To make it even clearer one could “Source “language of translation”, as opposed to “language of item” 

 

best,

R

Von: nathangibson <notifications@github.com> 
Gesendet: Mittwoch, 9. Januar 2019 15:03
An: biblia-arabica/srophe-eXist-app <srophe-eXist-app@noreply.github.com>
Cc: rvollandt <ronny.vollandt@lmu.de>; Mention <mention@noreply.github.com>
Betreff: Re: [biblia-arabica/srophe-eXist-app] Add language facet and change "Language" facet to "Citation Script" (#83)

 

Yes, I see your point. I think "Source Language" could be changed to "Translation Source Language" and the language facet you're currently adding could be "Language of Item". What do you think @rvollandt <https://github.com/rvollandt>  ?

**Comment by nathangibson** [comment]
Great. @wsalesky Can we change it to "Source Language of Translation"? And he-Arab is "Judaeo-Arabic". Thanks!

**Comment by wsalesky** [comment]
@nathangibson @rvollandt Done.
