### ISSUE TITLE
Pull in refactored Srophe app

### ISSUE THREAD

**Issue by nathangibson** [biblia-arabica/srophe-eXist-app#84]
Excited about the new, refactored Srophé!

When you think it is a good time, we could test this out in the dev branch (or another non-master branch) for Biblia Arabica. 

What is the correct procedure for this? I would be happy to learn how to do this (and also happy for you to be the one to actually do it if you have time). 

Is there any further abstraction we should be aware of, where we need to enter project-specific values?

Related: #1

**Comment by wsalesky** [comment]
@nathangibson If there is nothing more pressing I will tackle this one next.

**Comment by nathangibson** [comment]
Sounds good, thanks! 
I am checking the 1.0 things you fixed. Sorry for the slow responses. Have had to slow down on the bibliography due to some other things on my plate.

**Comment by wsalesky** [comment]
@nathangibson Okay, no rush. I will work on the email function today, and then get started with the refactor. Will keep you posted.

**Comment by wsalesky** [comment]
Okay, pulling in the refactored code today. Excuse any bumps.

**Comment by wsalesky** [comment]
@nathangibson I have updated the app, if you could take a quick look around and let me know if you find anything missing? If it looks good you can close the issue. Thanks.

**Comment by wsalesky** [comment]
@nathangibson Can I close this?

**Comment by nathangibson** [comment]
I assumed I needed to test this locally, but I see that you already loaded it onto the server! Thanks! It's been working so well that I didn't even notice!
