### ISSUE TITLE
Counter / Analytics

### ISSUE THREAD

**Issue by nathangibson** [biblia-arabica/srophe-eXist-app#85]
I wonder if we would want to monitor basic, anonymized usage. I believe you had google analytics for Syriaca, but I wonder if there's something less invasive that would just give us a basic idea of traffic. Definitely should be GDPR compliant. 
I came across https://statcounter.com. Do you have any recommendations?

**Comment by wsalesky** [comment]
@nathangibson I don't have anything better to recommend.  Would you like to try stat counter?

**Comment by nathangibson** [comment]
Hmm, OK, let's table this for the moment and I'll check with R what he wants to do. We can reopen it if needed.
