### ISSUE TITLE
counter 

### ISSUE THREAD

**Issue by rvollandt** [biblia-arabica/srophe-eXist-app#91]
Hi Winona, here my first "issue". Nathan has passed on the Github ownership to me. 

We need a counter of cleared references (these are the ones in the zotero published folder).
At the moment were have 238 cleared items verus 1546 in total in the whole library, planing to release them gradually in batches. 

To keep users updated, I'd suggest that we include a short notification that says "xxx out of xxx online." We could place it right before the "Introduction" section here: https://biblia-arabica.com/bibl/index.html

**Comment by wsalesky** [comment]
Hi @rvollandt finally getting to this. Are both numbers dynamic? Will the total number in Zotero change? Or can I use the 1546 as a static unchanging number. 

Thanks!

**Comment by wsalesky** [comment]
@rvollandt Added.

**Comment by rvollandt** [comment]
Dear Winona, 

 

Both will be dynamic. 

 

Thanks,

R

 

Von: Winona Salesky <notifications@github.com>
Antworten an: biblia-arabica/srophe-eXist-app <reply@reply.github.com>
Datum: Mittwoch, 5. Dezember 2018 um 15:46
An: biblia-arabica/srophe-eXist-app <srophe-eXist-app@noreply.github.com>
Cc: rvollandt <ronny.vollandt@lmu.de>, Mention <mention@noreply.github.com>
Betreff: Re: [biblia-arabica/srophe-eXist-app] counter (#91)

 

Hi @rvollandt finally getting to this. Are both numbers dynamic? Will the total number in Zotero change? Or can I use the 1546 as a static unchanging number.

Thanks!
