### ISSUE TITLE
Set nav-base in srophe-refactor to blank?

### ISSUE THREAD

**Issue by nathangibson** [biblia-arabica/srophe-eXist-app#93]
On production, we are currently using a blank nav-base, but srophe-refactor uses /exist/apps/ba. https://github.com/biblia-arabica/srophe-eXist-app/blob/36183450308566868e5175dc4b7e63266363b016/repo-config.xml#L26
Since we are merging srophe-refactor into master it should be blank, right? 
On my local test, I am getting 404s for links like http://localhost:8080/exist/apps/ba/$nav-base/bibl/browse.html?fq=;fq-Subjects:Generalia.

**Comment by wsalesky** [comment]
@nathangibson the current path is for testing locally, I will change it for deployment. Where are you encountering the link you posted? The one giving you the 404?
